name: fmtr
description: "Fmtr is a minimalistic text formatter. Sorts, cleans and prettifies JSON instantly."
publish_to: "none"
version: 1.0.4

environment:
  sdk: ^3.9.0
  flutter: ^3.35.0

dependencies:
  flutter:
    sdk: flutter

  provider: ^6.1.5+1
  shared_preferences: ^2.5.3

dev_dependencies:
  build_runner: ^2.10.1
  build_version: ^2.1.3
  test: ^1.26.3
  very_good_analysis: ^10.0.0

flutter:
  uses-material-design: true
