name: fmtr
description: "A text/data formatter."
publish_to: "none"
version: 2.0.3

environment:
  sdk: ^3.10.0
  flutter: ^3.38.0

dependencies:
  flutter:
    sdk: flutter

  provider: ^6.1.5+1
  shared_preferences: ^2.5.4

dev_dependencies:
  build_runner: ^2.10.5
  build_version: ^2.1.3
  test: ^1.28.0
  very_good_analysis: ^10.0.0

flutter:
  uses-material-design: true
