name: fmtr
description: "Sort, format, transform etc."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.9.0
  flutter: ^3.35.0

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^2.10.0
  build_version: ^2.1.3
  very_good_analysis: ^10.0.0

flutter:
  uses-material-design: true
